#-------------------------------
# Site Settings
title: Giovani Diaz Alfaro
logo: # You can add own logo. For example '/images/logo.png'.
description: My website
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: "About"
      url: "/about/"
    - title: "Research"
      url: "/contact/"
    - title: "Teaching"
      url: "/elements/"
    - title: "Pages"
      submenu:
      - url: "/if-you-cannot-do-great-things-do-small-things-in-a-great-way/"
        title: "Lifestyle"
      - url: "/you-must-be-the-change-you-wish-to-see-in-the-world/"
        title: "Workflow"


#-------------------------------
# Author Settings
author:
  author__name: Giovani Diaz Alfaro
  author__avatar: "/images/01-1.jpg"
  author__bio: I'm a cognitive scientist who's passionate about bringing projects to life! I love learning new things and jumping headfirst into solving problems.


#-------------------------------
# Links Section Settings
links:
  enable: true
  links__title: "Useful links"

links__item:
  - title: 10 Inspirational Books Every Creative Should Read
    description: Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
    image_url: "/images/110.jpg"
    image_alt: Inspirational books
    link: "https://twitter.com"

  - title: Creating stylised images from a photo
    description: Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
    image_url: "/images/111.jpg"
    image_alt: Illustrator
    link: "https://google.com"

  - title: Chill Movies for Couples to Watch on Date Night
    description: Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
    image_url: "/images/112.jpg"
    image_alt: Movies
    link: "https://www.netflix.com"

  - title: The 8 Best Exercises for Weight Loss
    description: Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
    image_url: "/images/114.jpg"
    image_alt: Best exercises
    link: "https://google.com"

  - title: Ask Me A Question On Instagram
    description: Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
    image_url: "/images/115.jpg"
    image_alt: Ask Me A Question
    link: "https://instagram.com"


#-------------------------------
# Hero Settings
hero:
  hero__title: Hi, I'm <span>Giovani Diaz Alfaro</span>. # Wrap text in a <span></span> tag to highlight and underline text.
  hero__job: Designer, Illustrator
  hero__description: I spend a lot of time creating cool things
  hero__button__text: Read about my past
  hero__button__link: "/about/"
  hero__image: "/images/01.jpg"


#-------------------------------
# Gallery Footer Section
gallery:
  enable: true
  gallery__title: Gallery
  gallery__columns: "3" # You can change the number of gallery columns
  gallery__images:
    - alt: "Rest"
      url: "/images/100.jpg"
    - alt: "Lifestyle"
      url: "/images/101.jpg"
    - alt: "Hobby"
      url: "/images/102.jpg"
    - alt: "Notes"
      url: "/images/103.jpg"
    - alt: "Rest"
      url: "/images/104.jpg"
    - alt: "Hobby"
      url: "/images/105.jpg"


#-------------------------------
# Newsletter
mailchimp:
  enable: true
  mailchimp__title: Subscribe to new posts # Add your Title
  mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
  mailchimp__identifier: "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp__button__text: Subscribe


#-------------------------------
# Social Icons Settings
social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com"}
- {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
- {icon: "fa-brands fa-discord", name: "Discord", link: "https://discord.com"}
- {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the author section and footer: - {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com}
# Other icons can be found at https://fontawesome.com/


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your form_id
  description: Atega comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Atega theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id